openapi: 3.0.3
info:
  version: 1.0.1
  description: |
    Health Planet OpenAPI Specification.

    <https://www.healthplanet.jp/apis/api.html>
  title: Health Planet API
servers:
  - url: 'https://www.healthplanet.jp'
    description: Production Server
paths:
  /oauth/auth:
    get:
      operationId: getOAuthAuth
      summary: OAuth アクセス許可
      tags:
        - oauth
      description: |
        ユーザに(Web ブラウザ経由で)アクセス許可を求める。

        ### API 制限

        適用対象外。
      externalDocs:
        description: Health Planet API 仕様書
        url: 'https://www.healthplanet.jp/apis/api.html'
      parameters:
        - in: query
          name: client_id
          description: アプリケーションの client_id 。
          schema:
            type: string
            required: true
            example: 0.demo.apps.healthplanet.jp
        - in: query
          name: redirect_uri
          description: |
            処理完了時、もしくはエラー発生時のリターン URL 。
            アプリケーション登録にて指定したドメインの URL もしくは https://www.healthplanet.jp/success.html が指定可能。
          schema:
            type: string
            required: true
            format: uri
            example: 'https://www.karadakarute.jp/tanita/'
        - in: query
          name: scope
          description: API の使用を許可する範囲。カンマ区切りで指定する。
          schema:
            type: array
            items:
              $ref: '#/components/schemas/EnumScope'
            required: true
            style: form
            explode: false
            example: 'innerscan,pedometer'
        - in: query
          name: response_type
          description: API のレスポンスを指定する。
          schema:
            $ref: '#/components/schemas/EnumResponseType'
            required: true
            example: code
  /oauth/token:
    post:
      operationId: postOAuthToken
      summary: OAuth リクエストトークン取得
      tags:
        - oauth
      description: |
        リクエストトークンを取得する。

        `GET /oauth/auth` を完了してから 10 分以内に完了させる必要がある。

        ### API 制限

        適用対象外。
      externalDocs:
        description: Health Planet API 仕様書
        url: 'https://www.healthplanet.jp/apis/api.html'
      requestBody:
        description: 会員情報
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequestPostOAuthToken'
            examples:
              デフォルト:
                value:
                  client_id: 0.demo.apps.healthplanet.jp
                  client_secret: 131156965920-RVcaOpgM7gelLJyFlprogo7VbvCLKBWxebANt
                  redirect_uri: 'https://www.karadakarute.jp/tanita/&code=qjzknJTyQPCdSj12Bq4xjGEe7RPnRUuMHRFwU5SdwRqa8'
                  code: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                  grant_type: authorization_code
      responses:
        '200':
          description: 処理成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsePostOAuthToken'
              examples:
                正常例:
                  value:
                    access_token: 0000000000000/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                    expires_in: 2592000
                    refresh_token: 0000000000000/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  '/status/innerscan.{format}':
    get:
      operationId: getStatusInnerscan
      summary: 体組成測定情報の取得
      tags:
        - status
      description: |
        体組成測定情報を取得する。

        この API を使用する場合は `GET /oauth/auth` にて `scope` : `innerscan`
        を指定する必要がある。

        ### API 制限

        1 時間あたり 60 回まで可能。
      externalDocs:
        description: Health Planet API 仕様書
        url: 'https://www.healthplanet.jp/apis/api.html'
      parameters:
        - in: path
          name: format
          description: レスポンスのフォーマット。
          required: true
          schema:
            $ref: '#/components/schemas/EnumFormat'
            required: true
            example: json
        - in: query
          name: access_token
          description: /oauth/token にて取得したトークン。
          schema:
            type: string
            required: true
            example: 0.demo.apps.healthplanet.jp
        - in: query
          name: date
          description: from to の日付タイプを指定する。
          schema:
            $ref: '#/components/schemas/EnumDateType'
            required: true
            example: 0
        - in: query
          name: from
          description: |
            取得期間 from を指定する。yyyyMMddHHmmss 形式で指定し、必ず from < to でなければならない。
            日付指定の from to は必ず 3 ヶ月以内を指定する必要がある。
            3 ヶ月を超える日付を指定した場合は、自動的に 3 ヶ月に補正される。
            未指定の場合は 3 ヶ月前が指定される。
          schema:
            type: string
            pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
            example: '20120101000000'
        - in: query
          name: to
          description: |
            取得期間 to を指定する。yyyyMMddHHmmss 形式で指定し、必ず from < to でなければならない。
            日付指定の from to は必ず 3 ヶ月以内を指定する必要がある。
            3 ヶ月を超える日付を指定した場合は、自動的に 3 ヶ月に補正される。
            未指定の場合は 3 ヶ月前が指定される。
          schema:
            type: string
            pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
            example: '20120301000000'
        - in: query
          name: tag
          description: 取得する測定部位を指定する。未指定の場合はデフォルトの値を取得する。カンマ区切りで指定する。
          schema:
            type: array
            items:
              $ref: '#/components/schemas/EnumInnerscanTag'
            style: form
            explode: false
            example: '6021,6022'
      responses:
        '200':
          description: 処理成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetStatusInnerscan'
              examples:
                正常例:
                  value:
                    $ref: '#/paths/~1status~1innerscan.%7Bformat%7D/get/responses/200/content/application~1xml/examples/%E6%AD%A3%E5%B8%B8%E4%BE%8B/value'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResponseGetStatusInnerscan'
              examples:
                正常例:
                  value:
                    birth_date: '19200709'
                    height: '170'
                    sex: male
                    data:
                      - date: '201008200628'
                        keydata: '62.15'
                        model: '01000023'
                        tag: '6021'
                      - date: '201008200628'
                        keydata: '13.00'
                        model: '01000023'
                        tag: '6022'
                      - date: '201008200443'
                        keydata: '20'
                        model: '00000000'
                        tag: '6021'
                      - date: '201008200443'
                        keydata: '20'
                        model: '00000000'
                        tag: '6022'
  '/status/pedometer.{format}':
    get:
      operationId: getStatusPedometer
      summary: 歩数測定情報の取得
      tags:
        - status
      description: |
        歩数測定情報を取得する。

        この API を使用する場合は `GET /oauth/auth` にて `scope` : `pedometer`
        を指定する必要がある。

        ### API 制限

        1 時間あたり 60 回まで可能。
      externalDocs:
        description: Health Planet API 仕様書
        url: 'https://www.healthplanet.jp/apis/api.html'
      parameters:
        - in: path
          name: format
          description: レスポンスのフォーマット。
          required: true
          schema:
            $ref: '#/components/schemas/EnumFormat'
            required: true
            example: json
        - in: query
          name: access_token
          description: /oauth/token にて取得したトークン。
          schema:
            type: string
            required: true
            example: 0.demo.apps.healthplanet.jp
        - in: query
          name: date
          description: from to の日付タイプを指定する。
          schema:
            $ref: '#/components/schemas/EnumDateType'
            required: true
            example: 0
        - in: query
          name: from
          description: |
            取得期間 from を指定する。yyyyMMddHHmmss 形式で指定し、必ず from < to でなければならない。
            日付指定の from to は必ず 3 ヶ月以内を指定する必要がある。
            3 ヶ月を超える日付を指定した場合は、自動的に 3 ヶ月に補正される。
            未指定の場合は 3 ヶ月前が指定される。
          schema:
            type: string
            pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
            example: '20120101000000'
        - in: query
          name: to
          description: |
            取得期間 to を指定する。yyyyMMddHHmmss 形式で指定し、必ず from < to でなければならない。
            日付指定の from to は必ず 3 ヶ月以内を指定する必要がある。
            3 ヶ月を超える日付を指定した場合は、自動的に 3 ヶ月に補正される。
            未指定の場合は 3 ヶ月前が指定される。
          schema:
            type: string
            pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
            example: '20120301000000'
        - in: query
          name: tag
          description: 取得する測定部位を指定する。未指定の場合はデフォルトの値を取得する。カンマ区切りで指定する。
          schema:
            type: array
            items:
              $ref: '#/components/schemas/EnumPedometerTag'
            style: form
            explode: false
            example: 6331
      responses:
        '200':
          description: 処理成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetStatusPedometer'
              examples:
                正常例:
                  value:
                    $ref: '#/paths/~1status~1pedometer.%7Bformat%7D/get/responses/200/content/application~1xml/examples/%E6%AD%A3%E5%B8%B8%E4%BE%8B/value'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResponseGetStatusPedometer'
              examples:
                正常例:
                  value:
                    birth_date: '19200709'
                    height: '170'
                    sex: male
                    data:
                      - date: '201008200628'
                        keydata: '12345'
                        model: '01000103'
                        tag: '6331'
                      - date: '201008200629'
                        keydata: '23456'
                        model: '01000103'
                        tag: '6331'
                      - date: '201008200630'
                        keydata: '34567'
                        model: '01000103'
                        tag: '6331'
  '/status/sphygmomanometer.{format}':
    get:
      operationId: getStatusSphygmomanometer
      summary: 血圧測定情報の取得
      tags:
        - status
      description: |
        血圧測定情報を取得する。

        この API を使用する場合は `GET /oauth/auth` にて `scope` : `sphygmomanometer`
        を指定する必要がある。

        ### API 制限

        1 時間あたり 60 回まで可能。
      externalDocs:
        description: Health Planet API 仕様書
        url: 'https://www.healthplanet.jp/apis/api.html'
      parameters:
        - in: path
          name: format
          description: レスポンスのフォーマット。
          required: true
          schema:
            $ref: '#/components/schemas/EnumFormat'
            required: true
            example: json
        - in: query
          name: access_token
          description: /oauth/token にて取得したトークン。
          schema:
            type: string
            required: true
            example: 0.demo.apps.healthplanet.jp
        - in: query
          name: date
          description: from to の日付タイプを指定する。
          schema:
            $ref: '#/components/schemas/EnumDateType'
            required: true
            example: 0
        - in: query
          name: from
          description: |
            取得期間 from を指定する。yyyyMMddHHmmss 形式で指定し、必ず from < to でなければならない。
            日付指定の from to は必ず 3 ヶ月以内を指定する必要がある。
            3 ヶ月を超える日付を指定した場合は、自動的に 3 ヶ月に補正される。
            未指定の場合は 3 ヶ月前が指定される。
          schema:
            type: string
            pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
            example: '20120101000000'
        - in: query
          name: to
          description: |
            取得期間 to を指定する。yyyyMMddHHmmss 形式で指定し、必ず from < to でなければならない。
            日付指定の from to は必ず 3 ヶ月以内を指定する必要がある。
            3 ヶ月を超える日付を指定した場合は、自動的に 3 ヶ月に補正される。
            未指定の場合は 3 ヶ月前が指定される。
          schema:
            type: string
            pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
            example: '20120301000000'
        - in: query
          name: tag
          description: 取得する測定部位を指定する。未指定の場合はデフォルトの値を取得する。カンマ区切りで指定する。
          schema:
            type: array
            items:
              $ref: '#/components/schemas/EnumSphygmomanometerTag'
            style: form
            explode: false
            example: '622E,622F,6230'
      responses:
        '200':
          description: 処理成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetStatusSphygmomanometer'
              examples:
                正常例:
                  value:
                    $ref: '#/paths/~1status~1sphygmomanometer.%7Bformat%7D/get/responses/200/content/application~1xml/examples/%E6%AD%A3%E5%B8%B8%E4%BE%8B/value'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResponseGetStatusSphygmomanometer'
              examples:
                正常例:
                  value:
                    birth_date: '19200709'
                    height: '170'
                    sex: male
                    data:
                      - date: '201008200628'
                        keydata: '120.12'
                        model: 01000097
                        tag: 622E
                      - date: '201008200628'
                        keydata: '80.12'
                        model: 01000097
                        tag: 622F
                      - date: '201008200443'
                        keydata: '60'
                        model: '00000000'
                        tag: '6230'
components:
  schemas:
    Innerscan:
      type: object
      description: |
        体組成測定情報の測定データ。
      required:
        - date
        - keydata
        - model
        - tag
      properties:
        date:
          type: string
          description: 測定日時。
          pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
        keydata:
          type: string
          description: 測定データ。
          format: float
        model:
          $ref: '#/components/schemas/EnumInnerscanModel'
          description: 測定機器名。
        tag:
          $ref: '#/components/schemas/EnumInnerscanTag'
          description: 測定部位。
    Pedometer:
      type: object
      description: |
        歩数測定情報の測定データ。
      required:
        - date
        - keydata
        - model
        - tag
      properties:
        date:
          type: string
          description: 測定日時。
          pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
        keydata:
          type: string
          description: 測定データ。
          format: float
        model:
          $ref: '#/components/schemas/EnumPedometerModel'
          description: 測定機器名。
        tag:
          $ref: '#/components/schemas/EnumPedometerTag'
          description: 測定部位。
    Sphygmomanometer:
      type: object
      description: |
        血圧測定情報の測定データ。
      required:
        - date
        - keydata
        - model
        - tag
      properties:
        date:
          type: string
          description: 測定日時。
          pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})/'
        keydata:
          type: string
          description: 測定データ。
          format: float
        model:
          $ref: '#/components/schemas/EnumSphygmomanometerModel'
          description: 測定機器名。
        tag:
          $ref: '#/components/schemas/EnumSphygmomanometerTag'
          description: 測定部位。
    EnumDateType:
      type: number
      description: |
        日付タイプ。

        | value |            |
        | :---- | :--------- |
        | 0     | 登録日付。 |
        | 1     | 測定日付。 |
      enum:
        - 0
        - 1
      x-enum-varnames:
        - registered
        - measured
    EnumFormat:
      type: string
      description: |
        レスポンスのフォーマット。
      enum:
        - json
        - xml
    EnumGrantType:
      type: string
      description: |
        API の付与タイプを指定する。

        | value              |                                    |
        | :----------------- | :--------------------------------- |
        | authorization_code | リクエストトークンの取得。         |
        | refresh_token      | リクエストトークンのリフレッシュ。 |
      enum:
        - authorization_code
        - refresh_token
    EnumInnerscanModel:
      type: string
      description: |
        体組成測定情報の測定機器名。

        | value    |                                     |
        | :------- | :---------------------------------- |
        | 00000000 | 手入力データ                        |
        | 01000001 | BC-501                              |
        | 01000002 | BC-502                              |
        | 01000003 | BC-503                              |
        | 01000022 | MC-180                              |
        | 01000023 | MC-190                              |
        | 01000024 | DC-320                              |
        | 01000067 | WB-510                              |
        | 01000072 | BC-504                              |
        | 01000074 | BC-567                              |
        | 01000075 | BC-569                              |
        | 01000076 | BC-308                              |
        | 01000077 | BC-309                              |
        | 01000079 | SC-330                              |
        | 01000080 | MC-980A/MC-980A plus/MC-980A-N plus |
        | 01000081 | BC-505                              |
        | 01000088 | RD-900                              |
        | 01000089 | RD-901                              |
        | 01000091 | DC-217A                             |
        | 01000092 | MC-780A/MC-780A-N                   |
        | 01000098 | RD-902                              |
        | 01000099 | RD-903                              |
        | 01000100 | BC-508                              |
        | 01000101 | RD-904                              |
        | 01000102 | RD-905                              |
        | 01000115 | DC-430A                             |
        | 01000117 | RD-800                              |
        | 01000124 | RD-E02                              |
        | 01000125 | RD-E03                              |
        | 01000121 | RD-E04                              |
        | 01000137 | RD-908                              |
        | 01000138 | RD-909                              |
        | 01000139 | DC-13C                              |
        | 01000140 | DC-270A/DC-270A-N                   |
        | 01000141 | RD-801                              |
        | 01000143 | BC-766                              |
        | 01000144 | BC-767                              |
        | 01000145 | BC-768                              |
        | 01000150 | RD-910                              |
        | 01000151 | RD-911                              |
        | 01000152 | RD-912                              |
        | 01000153 | RD-913                              |
        | 01000154 | RD-802                              |
      enum:
        - '00000000'
        - '01000001'
        - '01000002'
        - '01000003'
        - '01000022'
        - '01000023'
        - '01000024'
        - '01000067'
        - '01000072'
        - '01000074'
        - '01000075'
        - '01000076'
        - '01000077'
        - 01000079
        - 01000080
        - 01000081
        - 01000088
        - 01000089
        - 01000091
        - 01000092
        - 01000098
        - 01000099
        - '01000100'
        - '01000101'
        - '01000102'
        - '01000115'
        - '01000117'
        - '01000124'
        - '01000125'
        - '01000121'
        - '01000137'
        - 01000138
        - 01000139
        - '01000140'
        - '01000141'
        - '01000143'
        - '01000144'
        - '01000145'
        - '01000150'
        - '01000151'
        - '01000152'
        - '01000153'
        - '01000154'
      x-enum-varnames:
        - manual
        - BC-501
        - BC-502
        - BC-503
        - MC-180
        - MC-190
        - DC-320
        - WB-510
        - BC-504
        - BC-567
        - BC-569
        - BC-308
        - BC-309
        - SC-330
        - MC-980A
        - BC-505
        - RD-900
        - RD-901
        - DC-217A
        - MC-780A
        - RD-902
        - RD-903
        - BC-508
        - RD-904
        - RD-905
        - DC-430A
        - RD-800
        - RD-E02
        - RD-E03
        - RD-E04
        - RD-908
        - RD-909
        - DC-13C
        - DC-270A
        - RD-801
        - BC-766
        - BC-767
        - BC-768
        - RD-910
        - RD-911
        - RD-912
        - RD-913
        - RD-802
    EnumInnerscanTag:
      type: string
      description: |
        体組成測定情報の測定部位。

        | value |            | 単位 |
        | :---- | :--------- | :--- |
        | 6021  | 体重。     | kg   |
        | 6022  | 体脂肪率。 | %    |
      enum:
        - '6021'
        - '6022'
      x-enum-varnames:
        - weight
        - bodyFatPercentage
    EnumPedometerModel:
      type: string
      description: |
        の歩数測定情報測定機器名。

        | value    |              |
        | :------- | :----------- |
        | 00000000 | 手入力データ |
        | 01000006 | FB-723       |
        | 01000059 | FB-730       |
        | 01000087 | AM-150       |
        | 01000090 | AM-160       |
        | 01000103 | AM-161       |
      enum:
        - '00000000'
        - '01000006'
        - 01000059
        - 01000087
        - 01000090
        - '01000103'
      x-enum-varnames:
        - manual
        - FB-723
        - FB-730
        - AM-150
        - AM-160
        - AM-161
    EnumPedometerTag:
      type: string
      description: |
        歩数測定情報の測定部位。

        | value |        | 単位 |
        | :---- | :----- | :--- |
        | 6331  | 歩数。 | 歩   |
      enum:
        - '6331'
      x-enum-varnames:
        - steps
    EnumResponseType:
      type: string
      description: |
        API のレスポンスを指定する。
      enum:
        - code
    EnumScope:
      type: string
      description: |
        API の使用を許可する範囲。

        | value            |            |
        | :--------------- | :--------- |
        | innerscan        | 体組成情報 |
        | sphygmomanometer | 血圧情報   |
        | pedometer        | 歩数情報   |
        | smug             | 尿糖情報   |
      enum:
        - innerscan
        - sphygmomanometer
        - pedometer
        - smug
    EnumSex:
      type: string
      description: |
        測定機器名。

        | value  |        |
        | :----- | :----- |
        | male   | 男性。 |
        | female | 女性。 |
      enum:
        - male
        - female
    EnumSphygmomanometerModel:
      type: string
      description: |
        血圧測定情報の測定機器名。

        | value    |              |
        | :------- | :----------- |
        | 00000000 | 手入力データ |
        | 01000004 | BP-300       |
        | 01000005 | BP-301       |
        | 01000041 | A&D TM2655   |
        | 01000078 | BP-900       |
        | 01000097 | BP-302       |
      enum:
        - '00000000'
        - '01000004'
        - '01000005'
        - '01000041'
        - 01000078
        - 01000097
      x-enum-varnames:
        - manual
        - BP-300
        - BP-301
        - TM2655
        - BP-900
        - BP-302
    EnumSphygmomanometerTag:
      type: string
      description: |
        血圧測定情報の測定部位。

        | value |            | 単位 |
        | :---- | :--------- | :--- |
        | 622E  | 最高血圧。 | mmHg |
        | 622F  | 最低血圧。 | mmHg |
        | 6230  | 脈拍。     | bpm  |
      enum:
        - 622E
        - 622F
        - '6230'
      x-enum-varnames:
        - highestBloodPressure
        - lowestBloodPressure
        - pulse
    RequestPostOAuthToken:
      type: object
      required:
        - client_id
        - client_secret
        - redirect_uri
        - grant_type
      properties:
        client_id:
          type: string
          description: アプリケーションの client_id 。
        client_secret:
          type: string
          description: アプリケーションの client_secret 。
        redirect_uri:
          type: string
          format: uri
          description: |
            処理完了時、もしくはエラー発生時のリターン URL 。
            アプリケーション登録にて指定したドメインのURLもしくは https://www.healthplanet.jp/success.html が指定可能。
        grant_type:
          $ref: '#/components/schemas/EnumGrantType'
          description: API の付与タイプを指定する。
        code:
          type: string
          description: |
            /oauth/auth にて取得したコード。
            grant_type が authorization_code の時に必須。
        refresh_token:
          type: string
          description: |
            リフレッシュトークン。
            grant_type が refresh_token の時に必須。
    ResponseError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: エラーコード。
    ResponseGetStatusInnerscan:
      type: object
      required:
        - birth_date
        - height
        - sex
        - data
      properties:
        birth_date:
          type: string
          description: 誕生日。
          pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})/'
        height:
          type: string
          format: float
          description: 身長。
        sex:
          $ref: '#/components/schemas/EnumSex'
          description: 性別。
        data:
          type: array
          items:
            $ref: '#/components/schemas/Innerscan'
    ResponseGetStatusPedometer:
      type: object
      required:
        - birth_date
        - height
        - sex
        - data
      properties:
        birth_date:
          type: string
          description: 誕生日。
          pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})/'
        height:
          type: string
          format: float
          description: 身長。
        sex:
          $ref: '#/components/schemas/EnumSex'
          description: 性別。
        data:
          type: array
          items:
            $ref: '#/components/schemas/Pedometer'
    ResponseGetStatusSphygmomanometer:
      type: object
      required:
        - birth_date
        - height
        - sex
        - data
      properties:
        birth_date:
          type: string
          description: 誕生日。
          pattern: '/([0-9]{4})([0-9]{2})([0-9]{2})/'
        height:
          type: string
          format: float
          description: 身長。
        sex:
          $ref: '#/components/schemas/EnumSex'
          description: 性別。
        data:
          type: array
          items:
            $ref: '#/components/schemas/Sphygmomanometer'
    ResponsePostOAuthToken:
      type: object
      required:
        - access_token
        - expires_in
        - refresh_token
      properties:
        access_token:
          type: string
          description: アクセストークン。
        expires_in:
          type: number
          format: integer
          description: アクセストークンの有効期限。
        refresh_token:
          type: string
          description: リフレッシュトークン。
